name: Continuous Integration

on: push

env:
  Configuration: Release
  ContinuousIntegrationBuild: true

jobs:
  package:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    name: Run tests and create NuGet package
    outputs:
      version: ${{ steps.dotnet-pack.outputs.version }}
      nupkg-filename: ${{ steps.dotnet-pack.outputs.nupkg-filename }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      - run: dotnet restore --verbosity normal
      - run: dotnet build --verbosity normal
      - run: dotnet test --no-build --verbosity normal
      - run: dotnet pack --output . --no-build --verbosity normal
        id: dotnet-pack
      - uses: actions/upload-artifact@v2
        if: matrix.os == 'macos-latest'
        with:
          name: nuget-package
          path: ${{ steps.dotnet-pack.outputs.nupkg-filename }}
  publish:
    runs-on: macos-latest
    needs: package
    if: github.ref == 'refs/heads/prerelease' || startsWith(github.ref, 'refs/tags')
    name: Publish NuGet package
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: nuget-package
      - run: dotnet nuget push ${{ needs.package.outputs.nupkg-filename }} --source https://api.nuget.org/v3/index.json --api-key "${{ secrets.NUGET_API_KEY }}"
      - run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }} --store-password-in-clear-text
      - run: dotnet nuget push ${{ needs.package.outputs.nupkg-filename }} --source github
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Version ${{ needs.package.outputs.version }}
          body: ""
          draft: false
          prerelease: github.ref == 'refs/heads/prerelease'
