name: Continuous Integration

on: push

env:
  Configuration: Release
  ContinuousIntegrationBuild: true

jobs:
  package:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    name: Run tests and create NuGet package
    outputs:
      version: ${{ steps.dotnet-pack.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      - run: dotnet restore --verbosity normal
      - run: dotnet build --verbosity normal
      - run: dotnet test --no-build --verbosity normal
      - run: dotnet pack --no-build --verbosity normal
        id: dotnet-pack
      - uses: actions/upload-artifact@v2
        with:
          path: "**/*.nupkg"
  publish-release:
    runs-on: macos-latest
    needs: package
    if: startsWith(github.ref, 'refs/tags')
    name: Publish package on nuget.org
    steps:
      - run: dotnet nuget push "**/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key "${{ secrets.NUGET_API_KEY }}"
  publish-prerelease:
    runs-on: macos-latest
    needs: package
    if: github.ref == 'refs/heads/deploy'
    name: Publish package on github.com
    steps:
      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ needs.package.outputs.version }}",
              sha: context.sha
            })
      - run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }} --store-password-in-clear-text
      - run: dotnet nuget push "**/*.nupkg" --source github
