name: Continuous Integration

on: push

env:
  Configuration: Release
  ContinuousIntegrationBuild: true

jobs:
  test:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    name: Run tests and create NuGet package
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      - run: dotnet restore --verbosity normal
      - run: dotnet build --verbosity normal
      - run: dotnet test --no-build --verbosity normal
      - run: dotnet pack --no-build --verbosity normal
  publish:
    runs-on: macos-latest
    needs: test
    if: github.ref == 'refs/heads/deploy' || startsWith(github.ref, 'refs/tags')
    name: Publish NuGet package
    steps:
      - run: dotnet nuget push "**/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key "${{ secrets.NUGET_API_KEY }}"
